[package]
name = "centraldesk"
version = "0.3.7"
description = "Links úteis do Donato Hospital de Olhos"
authors = ["Donato Hospital de Olhos"]
edition = "2021"

[lib]
name = "centraldesk_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
serde_json = "1"

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["native-tls"] }
base64 = "0.22"
atomic-write-file = "0.3"
tokio-postgres = "0.7"
postgres-native-tls = "0.5"
native-tls = "0.2"
tokio = { version = "1", features = ["time", "macros"] }
