import { test, expect } from '@playwright/test';
test('login, rascunho, publicação e restauração de versão pelo painel',async ({page,request}) => {
  const errors: string[] = [];page.on('pageerror',error => errors.push(error.message));
  await page.goto('/admin/');
  await page.getByLabel('Usuário',{exact:true}).fill('test-admin');
  await page.getByLabel('Senha',{exact:true}).fill('Test-only-password-2026');
  await page.getByRole('button',{name:'Entrar no painel'}).click();
  await expect(page.getByRole('heading',{name:'Links da equipe'})).toBeVisible();
  await expect(page.locator('#links-table tr')).toHaveCount(11);
  await page.getByRole('button',{name:'+ Novo link'}).click();
  await page.getByLabel('Nome',{exact:true}).fill('PORTAL DA EQUIPE');
  await page.getByLabel('Endereço',{exact:true}).fill('example.com/equipe');
  await page.getByLabel('Descrição',{exact:true}).fill('Acesso para toda a equipe.');
  await page.getByLabel('Categoria',{exact:true}).fill('Equipe');
  await page.getByRole('button',{name:'Aplicar ao rascunho'}).click();
  await expect(page.locator('#links-table tr')).toHaveCount(12);
  const draftNames = await page.locator('#links-table .link-title strong').allTextContents();
  expect(draftNames).toEqual([...draftNames].sort((a,b) => a.localeCompare(b,'pt-BR')));
  await page.getByRole('button',{name:'Salvar rascunho'}).click();
  await expect(page.getByRole('status')).toContainText('Rascunho salvo');
  expect((await (await request.get('/api/links')).json()).links).toHaveLength(11);
  await page.reload();
  await expect(page.locator('#links-table tr')).toHaveCount(12);
  page.on('dialog',dialog => dialog.accept());
  await page.getByRole('button',{name:'Publicar alterações'}).click();
  await expect(page.getByRole('status')).toContainText('Versão 2 publicada');
  const catalog = await (await request.get('/api/links')).json();
  const names = catalog.links.map((link: {name:string}) => link.name);
  expect(names).toEqual([...names].sort((a,b) => a.localeCompare(b,'pt-BR')));
  expect(catalog.version).toBe(2);expect(catalog.links.find((link: {id:string}) => link.id === 'portal-da-equipe').id).toBe('portal-da-equipe');
  expect(catalog.links.find((link: {id:string}) => link.id === 'portal-da-equipe').url).toBe('https://www.example.com/equipe');
  await page.screenshot({path:'artifacts/admin-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Publicações',exact:true}).click();
  const latest = page.locator('.history-row').first();
  await expect(latest.locator('details')).toHaveAttribute('open','');
  await expect(latest).toContainText('Links adicionados');
  await expect(latest).toContainText('PORTAL DA EQUIPE');
  await expect(latest.locator('.history-changes')).not.toContainText('https://www.example.com/equipe');
  const restoreBox = await latest.getByRole('button',{name:'Restaurar como rascunho'}).boundingBox();
  const arrowBox = await latest.locator('.history-chevron').boundingBox();
  expect(restoreBox && arrowBox && restoreBox.x + restoreBox.width < arrowBox.x).toBeTruthy();
  const baseline = page.locator('.history-row').nth(1);
  await baseline.locator('summary').click();
  await expect(baseline).toContainText('Não há publicação anterior disponível para comparação.');
  await baseline.locator('summary').click();
  await expect(baseline.locator('details')).not.toHaveAttribute('open','');
  await page.screenshot({path:'artifacts/publications-expanded.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'artifacts/publications-mobile.png',fullPage:true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('.history-row').filter({hasText:'Versão 1'}).getByRole('button',{name:'Restaurar como rascunho'}).click();
  await expect(page.locator('#links-table tr')).toHaveCount(11);
  expect((await (await request.get('/api/links')).json()).version).toBe(2);
  await page.getByRole('button',{name:'Publicar alterações'}).click();
  await expect(page.getByRole('status')).toContainText('Versão 3 publicada');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'artifacts/admin-mobile.png',fullPage:true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button',{name:'Sair',exact:true}).click();
  await expect(page.getByRole('button',{name:'Entrar no painel'})).toBeVisible();
  expect(errors).toEqual([]);
});

test('catálogo publicado no painel é recebido pelo aplicativo e permanece disponível offline',async ({page,context,request}) => {
  await page.goto('/admin/');
  await page.getByLabel('Usuário',{exact:true}).fill('test-admin');await page.getByLabel('Senha',{exact:true}).fill('Test-only-password-2026');
  await page.getByRole('button',{name:'Entrar no painel'}).click();
  await page.getByRole('button',{name:'+ Novo link'}).click();
  await page.getByLabel('Nome',{exact:true}).fill('AAA LINK REPLICADO');
  await page.getByLabel('Endereço',{exact:true}).fill('https://example.com/replicado');
  await page.getByLabel('Categoria',{exact:true}).fill('Publicação central');
  await page.getByRole('button',{name:'Aplicar ao rascunho'}).click();
  page.on('dialog',dialog => dialog.accept());
  await page.getByRole('button',{name:'Publicar alterações'}).click();
  await expect(page.getByRole('status')).toContainText('publicada');
  const catalog = await (await request.get('/api/links')).json();
  const app = await context.newPage();
  await app.route('**/client-config.json',route => route.fulfill({json:{catalogUrl:'/live-catalog',pollIntervalMinutes:60}}));
  await app.route('**/live-catalog',async route => {
    const response = await route.fetch({url:'http://127.0.0.1:3031/api/links'});
    await route.fulfill({response});
  });
  await app.goto('http://127.0.0.1:1420/');
  await expect(app.getByRole('heading',{name:'AAA LINK REPLICADO'})).toBeVisible();
  await expect(app.locator('.link-card h3').first()).toHaveText('AAA LINK REPLICADO');
  await expect(app.locator('.catalog-status')).toContainText(`catálogo v${catalog.version}`);
  await app.route('**/live-catalog',route => route.abort());
  await app.reload();
  await expect(app.getByRole('status')).toContainText('links locais mantidos');
  await expect(app.getByRole('heading',{name:'AAA LINK REPLICADO'})).toBeVisible();
  await expect(app.locator('.link-card h3').first()).toHaveText('AAA LINK REPLICADO');
});

test('edição, categoria e ícone enviado são mantidos no banco',async ({page,request}) => {
  await page.goto('/admin/');
  await page.getByLabel('Usuário',{exact:true}).fill('test-admin');await page.getByLabel('Senha',{exact:true}).fill('Test-only-password-2026');
  await page.getByRole('button',{name:'Entrar no painel'}).click();
  await page.getByRole('button',{name:'Editar EAGLESOFT',exact:true}).click();
  await page.getByLabel('Nome',{exact:true}).fill('EAGLESOFT ATUALIZADO');
  await expect(page.getByLabel('Identificador')).toHaveAttribute('readonly','');
  await page.getByLabel('Ícone',{exact:true}).selectOption('upload');
  await page.locator('#icon-file').setInputFiles('public/logos/word.png');
  await expect(page.locator('#icon-preview')).toHaveAttribute('src',/^data:image\/png;base64,/);
  await page.getByRole('button',{name:'Aplicar ao rascunho'}).click();
  await page.getByRole('button',{name:'Renomear categoria',exact:true}).click();
  await page.getByLabel('Categoria atual').selectOption('Trabalho');await page.getByLabel('Novo nome').fill('Sistemas da instituição');
  await page.getByRole('button',{name:'Aplicar ao rascunho'}).click();
  page.on('dialog',dialog => dialog.accept());
  await page.getByRole('button',{name:'Publicar alterações'}).click();
  await expect(page.getByRole('status')).toContainText('publicada');
  const catalog = await (await request.get('/api/links')).json();
  const eaglesoft = catalog.links.find((link: {id:string}) => link.id === 'eaglesoft');
  expect(eaglesoft.name).toBe('EAGLESOFT ATUALIZADO');expect(eaglesoft.category).toBe('Sistemas da instituição');expect(eaglesoft.logo).toMatch(/^data:image\/png;base64,/);
  await page.getByRole('button',{name:'Publicações',exact:true}).click();
  const edited = page.locator('.history-row').first().locator('.change-group li').filter({hasText:'EAGLESOFT ATUALIZADO'});
  await expect(edited).toContainText('Nome, Ícone.');
  const categoryChanges = page.locator('.history-row').first().locator('.change-group').filter({hasText:'Categorias alteradas'});
  await expect(categoryChanges).toContainText('Trabalho → Sistemas da instituição');
  await expect(categoryChanges.locator('li')).toHaveCount(1);
  await expect(edited.locator('dl')).toHaveCount(0);
  await expect(page.locator('.history-row').first().locator('.history-changes')).not.toContainText('data:image');
});

test('cadastra e publica arquivo e pasta compartilhada com espaços e acentos',async ({page,request}) => {
  await page.goto('/admin/');
  await page.getByLabel('Usuário',{exact:true}).fill('test-admin');
  await page.getByLabel('Senha',{exact:true}).fill('Test-only-password-2026');
  await page.getByRole('button',{name:'Entrar no painel'}).click();
  for(const [name,address] of [
    ['LISTA DA REDE',String.raw`O:\GERAL\ÁREA DE TRANSFERENCIA\Lista Nova.xlsx`],
    ['PASTA DA REDE',String.raw`\\servidor\GERAL\Pasta da equipe`],
  ]) {
    await page.getByRole('button',{name:'+ Novo link'}).click();
    await page.getByLabel('Nome',{exact:true}).fill(name);
    await page.getByLabel('Endereço',{exact:true}).fill(address);
    await page.getByLabel('Categoria',{exact:true}).fill('Arquivos da equipe');
    await page.getByRole('button',{name:'Aplicar ao rascunho'}).click();
    await expect(page.locator('#edit-dialog')).not.toBeVisible();
  }
  page.on('dialog',dialog => dialog.accept());
  await page.getByRole('button',{name:'Publicar alterações'}).click();
  await expect(page.getByRole('status')).toContainText('publicada');
  const catalog = await (await request.get('/api/links')).json();
  expect(catalog.links.find((link: {id:string}) => link.id === 'lista-da-rede').url).toBe('file:///O:/GERAL/%C3%81REA%20DE%20TRANSFERENCIA/Lista%20Nova.xlsx');
  expect(catalog.links.find((link: {id:string}) => link.id === 'pasta-da-rede').url).toBe('file://servidor/GERAL/Pasta%20da%20equipe');
  // Restore the fixture for the next tests.
  await page.getByRole('button',{name:'Excluir LISTA DA REDE'}).click();
  await page.getByRole('button',{name:'Excluir PASTA DA REDE'}).click();
  await page.getByRole('button',{name:'Publicar alterações'}).click();
  await expect(page.getByRole('status')).toContainText('publicada');
});

test('ícones do menu são publicados pelo painel e continuam disponíveis offline',async ({page,context,request}) => {
  await page.goto('/admin/');
  await page.getByLabel('Usuário',{exact:true}).fill('test-admin');
  await page.getByLabel('Senha',{exact:true}).fill('Test-only-password-2026');
  await page.getByRole('button',{name:'Entrar no painel'}).click();
  await page.getByRole('button',{name:'Ícones do menu lateral',exact:true}).click();
  await page.getByLabel('Item do menu',{exact:true}).selectOption('Todos');
  await page.getByLabel('Ícone do menu',{exact:true}).selectOption('/donato-eye.svg');
  await page.getByRole('button',{name:'Aplicar ícone ao rascunho'}).click();
  await page.getByRole('button',{name:'Ícones do menu lateral',exact:true}).click();
  await page.getByLabel('Item do menu',{exact:true}).selectOption('Ferramentas Microsoft');
  await page.getByLabel('Ícone do menu',{exact:true}).selectOption('upload');
  await page.locator('#menu-icon-file').setInputFiles('public/logos/word.png');
  await expect(page.locator('#menu-icon-preview')).toHaveAttribute('src',/^data:image\/png;base64,/);
  await page.getByRole('button',{name:'Aplicar ícone ao rascunho'}).click();
  page.on('dialog',dialog => dialog.accept());
  await page.getByRole('button',{name:'Publicar alterações'}).click();
  await expect(page.getByRole('status')).toContainText('publicada');
  const published = await (await request.get('/api/links')).json();
  expect(published.categoryIcons.Todos).toBe('/donato-eye.svg');
  expect(published.categoryIcons['Ferramentas Microsoft']).toMatch(/^data:image\/png;base64,/);
  const app = await context.newPage();
  await app.route('**/client-config.json',route => route.fulfill({json:{catalogUrl:'/menu-catalog.json',pollIntervalMinutes:60}}));
  await app.route('**/menu-catalog.json',route => route.fulfill({json:published}));
  await app.goto('http://127.0.0.1:1420/');
  const all = app.getByRole('navigation').getByRole('button',{name:/Todos/});
  await expect(all.locator('img.category-icon')).toHaveAttribute('src','/donato-eye.svg');
  await expect(app.getByRole('navigation').getByRole('button',{name:/Ferramentas Microsoft/}).locator('img.category-icon')).toHaveAttribute('src',/^data:image\/png;base64,/);
  await app.route('**/menu-catalog.json',route => route.abort());
  await app.reload();
  await expect(all.locator('img.category-icon')).toHaveAttribute('src','/donato-eye.svg');
  await expect(app.getByRole('status')).toContainText('links locais mantidos');
  await app.close();
  // Restore the original icon so the shared preview is unchanged for following tests.
  await page.getByRole('button',{name:'Ícones do menu lateral',exact:true}).click();
  await page.getByLabel('Item do menu',{exact:true}).selectOption('Todos');
  await page.getByLabel('Ícone do menu',{exact:true}).selectOption('');
  await page.getByRole('button',{name:'Aplicar ícone ao rascunho'}).click();
  await page.getByRole('button',{name:'Ícones do menu lateral',exact:true}).click();
  await page.getByLabel('Item do menu',{exact:true}).selectOption('Ferramentas Microsoft');
  await page.getByLabel('Ícone do menu',{exact:true}).selectOption('');
  await page.getByRole('button',{name:'Aplicar ícone ao rascunho'}).click();
  await page.getByRole('button',{name:'Publicar alterações'}).click();
  await expect(page.getByRole('status')).toContainText('publicada');
});


test('SVG de URL e arquivo enviado é convertido para PNG antes de publicar',async ({page,request}) => {
  await page.route('https://icons.example/microsoft.svg*',route => route.fulfill({contentType:'image/svg+xml',headers:{'Access-Control-Allow-Origin':'*'},body:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 23 23"><path fill="#f35325" d="M1 1h10v10H1z"/><path fill="#81bc06" d="M12 1h10v10H12z"/><path fill="#05a6f0" d="M1 12h10v10H1z"/><path fill="#ffba08" d="M12 12h10v10H12z"/></svg>'}));
  await page.goto('/admin/');
  await page.getByLabel('Usuário',{exact:true}).fill('test-admin');
  await page.getByLabel('Senha',{exact:true}).fill('Test-only-password-2026');
  await page.getByRole('button',{name:'Entrar no painel'}).click();
  await page.getByRole('button',{name:'Ícones do menu lateral',exact:true}).click();
  await page.getByLabel('Item do menu',{exact:true}).selectOption('Ferramentas Microsoft');
  await page.getByLabel('Ícone do menu',{exact:true}).selectOption('custom');
  await page.locator('#menu-icon-url').fill('https://icons.example/microsoft.svg?utm_source=test');
  await page.getByRole('button',{name:'Aplicar ícone ao rascunho'}).click();
  await expect(page.locator('#category-icon-dialog')).not.toBeVisible();
  await page.getByRole('button',{name:'Ícones do menu lateral',exact:true}).click();
  await page.getByLabel('Item do menu',{exact:true}).selectOption('Todos');
  await page.getByLabel('Ícone do menu',{exact:true}).selectOption('upload');
  await page.locator('#menu-icon-file').setInputFiles('public/donato-eye.svg');
  await expect(page.locator('#menu-icon-preview')).toHaveAttribute('src',/^data:image\/png;base64,/);
  await page.getByRole('button',{name:'Aplicar ícone ao rascunho'}).click();
  page.on('dialog',dialog => dialog.accept());
  await page.getByRole('button',{name:'Publicar alterações'}).click();
  await expect(page.getByRole('status')).toContainText('publicada');
  const catalog = await (await request.get('/api/links')).json();
  expect(catalog.categoryIcons['Ferramentas Microsoft']).toMatch(/^data:image\/png;base64,/);
  expect(catalog.categoryIcons.Todos).toMatch(/^data:image\/png;base64,/);
});
